import { z } from "genkit";
import { ai } from "./ai";
import { firestoreMock } from "./firestoreMock";
import { recommendExperiencesForUser, findSimilarTravelers } from "./graphQueries";
import { mockBookingProvider } from "./mockProvider";
import { ChatMessage, ChatSession } from "./types";

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 1 ▸ Define Genkit Tools for the Agent
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const getUserProfileTool = ai.defineTool(
  {
    name: "getUserProfile",
    description: "Fetches the detailed traveler profile (interests, travel style, companion, budget) for the given user.",
    inputSchema: z.object({ userId: z.string() }),
    outputSchema: z.any(),
  },
  async (input) => {
    const profile = await firestoreMock.profiles.get(input.userId);
    if (!profile) {
      return { error: "No profile found. The user needs to complete the onboarding first." };
    }
    return profile;
  }
);

export const recommendExperiencesTool = ai.defineTool(
  {
    name: "recommendExperiences",
    description: "Queries the global graph database to recommend highly personalized travel experiences based on overlapping interest tags.",
    inputSchema: z.object({ userId: z.string() }),
    outputSchema: z.any(),
  },
  async (input) => {
    return await recommendExperiencesForUser(input.userId);
  }
);

export const findSimilarTravelersTool = ai.defineTool(
  {
    name: "findSimilarTravelers",
    description: "Queries the global graph database to discover other travelers with similar interests and travel styles who are on similar journeys.",
    inputSchema: z.object({ userId: z.string() }),
    outputSchema: z.any(),
  },
  async (input) => {
    return await findSimilarTravelers(input.userId);
  }
);

export const checkAvailabilityTool = ai.defineTool(
  {
    name: "checkAvailability",
    description: "Checks real-time availability of an experience with the booking provider catalog.",
    inputSchema: z.object({
      experienceId: z.string().describe("ID of the experience to check"),
      date: z.string().describe("Date in YYYY-MM-DD format"),
      slot: z.string().describe("Time slot (e.g. '09:00', '18:00')"),
      partySize: z.number().int().positive().describe("Number of travelers in the party"),
    }),
    outputSchema: z.any(),
  },
  async (input) => {
    return await mockBookingProvider.checkAvailability(
      input.experienceId,
      input.date,
      input.slot,
      input.partySize
    );
  }
);

export const bookExperienceTool = ai.defineTool(
  {
    name: "bookExperience",
    description: "Agentically reserves and confirms a booking for a travel experience using secure booking channels.",
    inputSchema: z.object({
      userId: z.string().describe("ID of the user making the booking"),
      experienceId: z.string().describe("ID of the experience to book"),
      date: z.string().describe("Date in YYYY-MM-DD format"),
      slot: z.string().describe("Selected time slot"),
      partySize: z.number().int().positive().describe("Number of travelers"),
    }),
    outputSchema: z.any(),
  },
  async (input) => {
    try {
      const booking = await mockBookingProvider.createBooking(
        input.userId,
        input.experienceId,
        input.date,
        input.slot,
        input.partySize
      );
      return {
        success: true,
        message: `Successfully booked "${booking.experienceName}" for ${booking.partySize} travelers on ${booking.bookingDate} at ${booking.slot}!`,
        bookingDetails: booking,
      };
    } catch (err: any) {
      return {
        success: false,
        error: err.message || "Failed to create booking.",
      };
    }
  }
);

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 2 ▸ Define the Travel Assistant Flow (Multi-turn Chat)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const ChatInputSchema = z.object({
  userId: z.string(),
  sessionId: z.string(),
  message: z.string(),
});

export const ChatOutputSchema = z.object({
  responseMessage: z.string().describe("The text response generated by the assistant"),
  chatHistory: z.array(z.custom<ChatMessage>()),
});

export const travelAssistantFlow = ai.defineFlow(
  {
    name: "travelAssistantFlow",
    inputSchema: ChatInputSchema,
    outputSchema: ChatOutputSchema,
  },
  async (input) => {
    console.log(`💬 Processing message for session ${input.sessionId} (user ${input.userId})...`);

    // 1. Fetch or initialize chat session history from mock Firestore
    let session = await firestoreMock.sessions.get(input.sessionId);
    if (!session) {
      session = {
        sessionId: input.sessionId,
        userId: input.userId,
        messages: [],
        createdAt: new Date().toISOString(),
      };
    }

    // 2. Append new user message to session history
    session.messages.push({
      role: "user",
      content: input.message,
      timestamp: new Date().toISOString(),
    });

    // 3. Build system instructions
    const systemPrompt = `You are ANA (Anatolian Navigator AI), a warm, inspiring travel concierge and booking assistant for Türkiye.
You guide travelers through their journey, recommend personalized experiences, connect them with like-minded travelers, and agentically handle booking arrangements.

Your Guidelines:
1. Always start by fetching the user's profile using \`getUserProfile\` to personalize your response.
2. Recommend experiences using \`recommendExperiences\`. Mention that recommendations are tailored using our Neo4j Graph DB!
3. If they are looking for travel buddies, use \`findSimilarTravelers\` to suggest connections.
4. When they decide on an experience, check availability first via \`checkAvailability\`.
5. If available, confirm they want to proceed and book it agentically using \`bookExperience\`. Provide booking details clearly.
6. Speak in a helpful, knowledgeable concierge tone. Support their planning step-by-step.`;

    // 4. Map saved messages to the format expected by Genkit's generate history
    const genkitHistory = session.messages.map((m) => ({
      role: m.role,
      content: [{ text: m.content }],
    }));

    // 5. Generate assistant response with mock fallback if API key is missing
    let replyContent = "";
    try {
      const response = await ai.generate({
        system: systemPrompt,
        history: genkitHistory.slice(0, -1), // Pass past history
        prompt: input.message, // Pass current message
        tools: [
          getUserProfileTool,
          recommendExperiencesTool,
          findSimilarTravelersTool,
          checkAvailabilityTool,
          bookExperienceTool,
        ],
        config: {
          temperature: 0.7,
        },
      });
      replyContent = response.text;
    } catch (e: any) {
      if (
        e.status === "FAILED_PRECONDITION" || 
        e.message?.includes("API key") || 
        e.originalMessage?.includes("API key")
      ) {
        console.warn("⚠️ [Mock AI Mode] No Google AI Studio API Key configured. Simulating ANA's response...");
        const msg = input.message.toLowerCase();
        if (msg.includes("profile") || msg.includes("recommend")) {
          replyContent = `Hi David! I've fetched your travel profile. You are registered as an Adventure traveler with a Luxury budget. Based on our Neo4j Graph DB connections, I highly recommend the **Cappadocia Hot Air Balloon Flight** (Adventure) and the **Guided Hiking Tour of Rose & Red Valleys** (Adventure) as they perfectly match your interests in hiking, nature, and adventure! I also found Alice Smith who shares 4 of your interests. Would you like me to check availability for any of these tours?`;
        } else if (msg.includes("book") || msg.includes("balloon")) {
          // Call mock booking provider programmatically to simulate agentic tool usage
          const booking = await mockBookingProvider.createBooking(input.userId, "exp_balloon_cappadocia", "2026-05-20", "05:00", 1);
          replyContent = `Perfect choice, David! I checked with our booking provider, and slots are available for tomorrow, May 20th. I have agentically processed your payment and confirmed your booking! 🎉\n\n**Booking Details:**\n- **Experience:** ${booking.experienceName}\n- **Date & Slot:** ${booking.bookingDate} at ${booking.slot}\n- **Booking ID:** ${booking.id}\n- **Total Price:** $${booking.totalPriceUSD} USD\n\nYour tickets are secured, and you are ready to fly over Cappadocia at sunrise!`;
        } else {
          replyContent = `Hello! I am ANA, your Anatolian AI guide. Let me know if you would like me to fetch your profile, recommend personalized experiences from our Neo4j graph database, or agentically book tours for you.`;
        }
      } else {
        throw e;
      }
    }

    // 6. Save assistant's reply to session history
    session.messages.push({
      role: "model",
      content: replyContent,
      timestamp: new Date().toISOString(),
    });

    await firestoreMock.sessions.set(input.sessionId, session);

    console.log(`✅ Message processed successfully. Reply length: ${replyContent.length}`);

    return {
      responseMessage: replyContent,
      chatHistory: session.messages,
    };
  }
);
